name: sopaki_app
description: "sopaki agent"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  auto_route: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  form_validator: ^2.1.1
  iconsax_plus: ^1.0.0
  intl: ^0.20.2
  dio: ^5.0.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  get_it: ^7.7.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.1
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.3
  loading_animation_widget: ^1.3.0
  mobile_scanner: ^6.0.7
  image_picker: ^1.1.2
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  flutter_expandable_fab: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.0
  logger: ^2.5.0
  device_info_plus: ^10.1.2
  rflutter_alert: ^2.0.7
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_tile_caching: ^10.0.0
  flutter_map_marker_cluster: ^1.4.0
  flutter_polyline_points: ^3.0.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter


  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  test: ^1.25.7

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: AvenirKw
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf


fluttergen:
  output: lib/src/generated
  line_length: 120

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: I18n
  main_locale: en
  arb_dir: lib/src/core/i18n/l10n
  output_dir: lib/src/core/i18n